### ISSUE TITLE
Rospy for Python 3

### ISSUE THREAD

**Issue by rivermont** [ros/ros_comm#1208]
It seems the only way to use Python 3.x with rospy is to rebuild all of the ROS packages from source, forcing Python 3. However this seems like it would cause a lot of compatibility issues. Is there any other way to create nodes in Python 3 for ROS?

**Comment by dirk-thomas** [comment]
Using a consistent version of Python throughout all packages is certainly the recommended way.

If you know that all recursive Python code of your node works with Python 2 as well as 3 you can just use a Python 3 shebang line for your node and as long as all dependencies are being found your node should work fine. That "works" because ROS add the Python code of all ROS packages to the `PYTHONPATH`. For some system dependencies (like `catkin-pkg-modules`, `python-yaml`) you will have to also install the Python 3 equivalent.

In general since this is more a question rather than an action item (like a bug, feature request, etc.) I will close this since there is nothing to do about it in this repo. In the future we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

**Comment by AlexisTM** [comment]
Note: `python3-catkin-pkg-modules` cannot be installed because the Python2 version is installed.

Once we intall `ros-melodic-ros-base`, the Python2 versions are installed and we cannot install the Python3 versions.

```bash
The following packages have unmet dependencies:
 python3-rosdep : Depends: python3-catkin-pkg (>= 0.4.0) but it is not going to be installed
                  Conflicts: python3-rosdep2 but 0.11.8-1 is to be installed
 python3-rosdep2 : Depends: python3-catkin-pkg but it is not going to be installed
 python3-rosinstall : Depends: python3-catkin-pkg but it is not going to be installed
 python3-rosinstall-generator : Depends: python3-catkin-pkg (>= 0.1.28) but it is not going to be installed
 python3-rospkg : Depends: python3-catkin-pkg but it is not going to be installed
```

**Comment by dirk-thomas** [comment]
> `python3-catkin-pkg-modules` cannot be installed because the Python2 version is installed.

That statement is incorrect. `python-catkin-pkg-modules` and `python3-catkin-pkg-modules` can absolutely be installed side-by-side. These packages only contain the Python modules of `catkin_pkg` but not the command line tools.

The packages `python-catkin-pkg` and `python3-catkin-pkg` can't be installed side-by-side since they provide the same command line tools - just with a different shebang line.

**Comment by Neuan** [comment]
Any suggestion on how to install rospy inside a Python3 virtual environment?
Thanks.
