### ISSUE TITLE
Include remote machine "y.launch" and run it from local "x.launch"

### ISSUE THREAD

**Issue by ugnelis** [ros/ros_comm#1215]
Cannot launch remote machine "launch" file from local machine. Is there a way to accomplish that?
```xml
<launch>
  <machine name="machine_y" address="192.168.1.130" env-loader="/opt/ros/fuerte/env.sh"/>
  <include file="/path/to/remote/y.launch" machine="machine_y"/> <!-- doesn't work -->
  <node pkg="package_y" name="package_y_name" machine="machine_y"/> <!-- works -->
</launch>
```

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
