### ISSUE TITLE
Problem with rospy

### ISSUE THREAD

**Issue by aefka** [ros/ros_comm#1299]
Hello

I am working with V-REP and ROS. I have to write script which will be moving the model in V-REP. I can move this model thanks e.g: 

    rostopic pub -1 /cmd_vel geometry_msgs/Twist '{linear: {x: -3.0, y: -3.0}}'
I set velcities on -3, and model is moving. Now I have to do the same in Python, but I am newbie progamming.
 
code: 

 ```
  #!/usr/bin/env python
    import rospy
    from std_msgs.msg importFloat32
    #added
    from geometry_msgs.msg import Twist 
    
    
    def callback(data):
        global msg
        global pub
        if data.data=="Unknown":
            rospy.loginfo("Classifiers output: %s in unknown" % data.data)
            msg.linear.x = 2
            msg.linear.y = 2
            msg.angular.z = 0
            speed = 0.4 
            rospy.loginfo("checking for cmd" + str(msg.linear))
            pub.publish(msg)
        elif data.data=="Check":
            rospy.loginfo("Classifiers output: %s in check" % data.data)
        else:      
            rospy.loginfo("Classifiers output: %s and not unknown or check" % data.data)
    

    
    
    def listener():
         global msg
         rospy.init_node('listener', anonymous=True)
         msg = Twist()
         rospy.Subscriber("ccc", Float32, callback)
         global pub
         pub = rospy.Publisher('cmd_vel', Twist, queue_size=10) # move instantiation of publisher
         rospy.spin()
    
    
    if __name__ == '__main__':
        listener()

```

After starting this program,no error appears, however the model does not move. 
Can someone help me correct the code? 

Next I have to subscribe  from V-REP from topic which variable is Float32
In Terminal I am doing this thanks: 

 `   Rostopic echo /frontUS `

But the most important thing is to move model :/ 

Regards

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
