### ISSUE TITLE
Regression in 1.12.13: rosout node spins rather than blocking and waiting, using 100% CPU

### ISSUE THREAD

**Issue by NickZ** [ros/ros_comm#1343]
Introduced in faab4cbc63d6c750c6dc6d050f6268dd19a2bc68. This is a bug in the roscpp client.

In `callAvailable()` in callback_queue.cpp, if no callback is available, `wait_for()` (located in boost_161_pthread_condition_variable_fwd.h) is called on the condition variable, and is told to wait for a specified amount of time (usually 0.1 seconds). However, instead of waiting for the specified amount of time, it returns immediately, turning this into a spin wait rather than a blocking wait. This leads to the rosout node chewing up 100% of the CPU core.

**Comment by NickZ** [comment]
The issue is that, on linux systems and every other platform with monotonic clock set, `wait_for()` calls `steady_clock.now()` to get the system time. "steady_clock" is a monotonic time clock that is a relative clock (usually whenever the system booted up.) However, `wait_for() => wait_until() => do_wait_until()` ultimately calls `pthread_cond_timedwait()` with a timeout value based on that relative clock value. `pthread_cond_timedwait()` only takes in absolute system time values. Thus, it immediately returns with a timeout, since the relative time is guaranteed to be smaller than the system time.

**Comment by NickZ** [comment]
Ok, I've discovered the root cause. It's nasty, nasty compiler/linker behavior. Also, the bug is different across boost versions.

`pthread_cond_timedwait()` does not normally take monotonic clock values. However, when creating the condition_variable, it can set the condition attributes of the pthread condition to accept Monotonic clock values: 
![image](https://user-images.githubusercontent.com/1124174/37015443-0e2064e2-20bc-11e8-994b-5fb7bf7d0617.png)

However, this never actually gets called.

**On systems that have boost <1.61 (tested on Ubuntu 16.04)**, it's supposed to use the `condition_variable` defined in boost_161_pthread_condition_variable_fwd.h. However, the constructor for the condition variable as defined in that file does not actually get used, it uses the constructor in the system boost library, which does not call the pthread_cond_init function: 

![image](https://user-images.githubusercontent.com/1124174/37015497-74b27808-20bc-11e8-9d45-d9677c2a320c.png)

This is especially bizarre, since I have observed in debugging that it's using the `wait_for()` and `wait_until()` function calls in boost_161_pthread_condition_variable_fwd.h.

**On systems that have boost >=1.61 (tested on Ubuntu 18.04)**, it uses the system boost library. Normally, the pthread condition attribute would be set, since we set `BOOST_THREAD_HAS_CONDATTR_SET_CLOCK_MONOTONIC` in callback_queue.cpp. However, we can see that's not the case: 
![image](https://user-images.githubusercontent.com/1124174/37015642-411e8d28-20bd-11e8-9b50-7868c55bbd4e.png)
It uses the preprocessor else block instead. This is even more bizarre, since it hits numerous other code blocks that require that preprocessor definition. 

I don't know how to fix this, unfortunately, but hopefully someone here knows enough compiler/linker juju to fix it.

**Comment by flixr** [comment]
> However, wait_for() => wait_until() => do_wait_until() ultimately calls pthread_cond_timedwait() with a timeout value based on that relative clock value. pthread_cond_timedwait() only takes in absolute system time values. Thus, it immediately returns with a timeout, since the relative time is guaranteed to be smaller than the system time.

That should not really be possible to happen, `wait_for(duration)` always basically calls `wait_until(current_time + duration)` where `current_time` is either derived from system clock or monotonic clock dependent on the `BOOST_THREAD_HAS_CONDATTR_SET_CLOCK_MONOTONIC` define.

I cannot reproduce this issue, could you please provide some more information?

Tried with latest versions from shadow-fixed (ros-kinetic-roscpp 1.12.13 and so on) and the simple listener from ros-kinetic-roscpp-tutorials and it works fine.

**Comment by kjaget** [comment]
I saw this same issue building roscpp from source just recently.  Same symptom - near 100% cpu usage in every node. Reverting to 1.12.12 fixed the problem immediately.  I can pull info off my system to help diagnose but I'm not sure what might be useful.  It is a Ubuntu 16.04 system which is up to date with apt-get but with not much custom built - let me know what info would be useful.

**Comment by NickZ** [comment]
I did some further testing, and apparently this issue does not occur if you build the entire ros_comm stack from scratch; It only occurs if you either already have the base 1.12.12 system packaging installed and you only build ros_comm and roscpp_core, or if you rebuild only the ros_comm part for a source installation. So, some sort of compiler/linker issue. I have to set up some sort of testing apparatus to track the cause down with more specificity.

**Comment by flixr** [comment]
Hm.. strange. I still can not reproduce this...
What I tried on Ubuntu 16.04 with the released kinetic packages (1.12.12) as base:
- create a clean catkin workspace based on /opt/ros/kinetic
- add `ros_comm`, `roscpp_core` and `ros_tutorials` repos with kinetic-devel branch
- build only rostime, roscpp and ros_tutorials
- run any of the talker/listeners from the tutorials

I built the parts to be tested and used the rest from /opt/ros/kinetic
```
catkin build --no-deps rostime
catkin build --no-deps roscpp
catkin build --no-deps roscpp_tutorials
```
It still works as expected, regardless if I run the listener from the binaries or the rebuilt tutorials...

**Comment by NickZ** [comment]
Ok, this is what I did to reproduce consistently:

1. Get a fresh Ubuntu 16.04 image (in either a VM, bare-metal, or a lxc/docker container).
2. Install the ros-base package (`sudo apt-get install ros-kinetic-ros-base`)
3. create a clean catkin workspace based on /opt/ros/kinetic
4. Populate it with `ros_comm`, `roscpp_core`, and `ros_tutorials` repos on the kinetic-devel branch
5. Either run `catkin_make`, or use the build process you describe above, I've reproduced it with both.
6. source devel/setup.bash, run `roscore`, observe the cpu in top.

**Comment by flixr** [comment]
Could it be that this is a problem with `catkin_make`, as I was using `catkin` from the `catkin_tools` package...
Does this problem also occur with `catkin_make_isolated`?

**Comment by NickZ** [comment]
as I've said, I've done this using both the build process described in your post, just using`catkin`, and with `catkin_make`. I get the same bug. 

It does not occur when I have built the whole ros_comm stack from source, using `catkin_make_isolated`.

**Comment by flixr** [comment]
Hm.... I used the install space when testing this... will try again with the devel space.
But this still sounds like basically a known issue with `caktin_make` to me...

**Comment by NickZ** [comment]
Just for reference, what catkin bugs should I be aware of?

**Comment by flixr** [comment]
Should have phrased it more precisely: known limitation.
Currently I can't find this anywhere in the catkin docs, but it's nicely summarized here: http://catkin-tools.readthedocs.io/en/latest/migration.html

**Comment by flixr** [comment]
Ok, I can reproduce it with the Dockerfile https://gist.github.com/flixr/77e36cfac037700080efd937148b0f7f

To test this
```
docker build -t test_ros_comm .
docker run -it test_ros_comm
```
and observe the high cpu load as you said...

I have no clue why this is happening though.

**Comment by flixr** [comment]
It's especially weird because we have over 100 devices running with https://github.com/ros/ros_comm/pull/1250 without problems.
Although that is still on indigo, I just built a new ros-indigo-roscpp debian package on our CI (based on the ros:indigo-perception image) and installed that updated deb in our systems.

**Comment by fujitatomoya** [comment]
+1

**Comment by fujitatomoya** [comment]
core tells us the following link problem, we are not sure the root cause of this yet.

when problem observed, libboost_thread is used as following,
which means no pthread_condattr_setclock is issued before.

#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225 
#1 0x00007fcbd757ebdd in boost::condition_variable::do_wait_until (this=0x10022e8, m=..., timeout=...) at /usr/include/boost/thread/pthread/condition_variable.hpp:108 

when problem is NOT observed,
internal class is used with pthread_condattr_setclock.

#0 pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225 
#1 0x00007fc1f5da5501 in boost::condition_variable::do_wait_until (this=0x74c2e8, m=..., timeout=...)
at  /home/sharedata/Projects/ROS1/src/ros_comm/clients/roscpp/include/boost_161_pthread_condition_variable.h:111

**Comment by fujitatomoya** [comment]
so far, cannot find root cause.
does anyone have clue for this?

**Comment by meyerj** [comment]
I was also affected by this issue after I compiled the kinetic version of roscpp from source and tried to dig deeper based on the previous observations posted here.

My preliminary conclusion is that the approach taken in #1014 and #1250, to backport the `boost::condition_variable` without changing the same symbol name, is dangerous for the following reasons:

1. Mixing units where `BOOST_THREAD_HAS_CONDATTR_SET_CLOCK_MONOTONIC` is set in one, but not in another, are not supported by Boost: https://svn.boost.org/trac10/ticket/12389
   It is supposed to be a system-wide definitions.
2. It is assumed that the constructors and member functions of [TimerManager](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/include/ros/timer_manager.h#L221-L226) and [CallbackQueue](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/src/libros/callback_queue.cpp#L55-L59) are only defined in certain compilation units where `BOOST_THREAD_HAS_CONDATTR_SET_CLOCK_MONOTONIC` is set. I did not find any other definition than in [internal_timer_manager.cpp](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/src/libros/internal_timer_manager.cpp#L28-L31) and [callback_queue.cpp](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/src/libros/callback_queue.cpp#L35-L38), but I might have missed something.

   Unfortunately that is not necessarily the case and there are other possibilities how the two classes can be instantiated. It is only the definition of `boost::condition_variable` seen by the compilation unit where the constructor of `TimerManager` or `CallbackQueue` is defined that decides which implementation of the `condition_variable` constructor gets called:

   - Obviously any `TimerManager<T, D, E>` instance other than the one created by [initInternalTimerManager()](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/src/libros/internal_timer_manager.cpp#L58) in [internal_timer_manager.cpp](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/src/libros/internal_timer_manager.cpp) calls the normal constructor of `boost::condition_variable`.
   - Even `SteadyTimer` does not define the macro and therefore instantiates a normal, non-monotonic instance of `boost::condition_variable` when creating a new global `TimerManager<SteadyTime, WallDuration, SteadyTimerEvent>` instance in [SteadyTimer::Impl::start()](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/src/libros/steady_timer.cpp#L135).
   - Implicitly defined copy- or move-constructors could also trigger a construction of `boost::condition_variable` in compilation units without `BOOST_THREAD_HAS_CONDATTR_SET_CLOCK_MONOTONIC`. However. this should not be the problem here because `boost::condition_variable` and `boost::mutex` are non-copyable and non-movable and so are `TimerManager<T,D,E>` and `CallbackQueue`.

3. Inlining. I assume that's the main issue here. These two classes are not the only ones within `roscpp` that have `boost::condition_variable` members. There is also one in [RosoutAppender](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/include/ros/rosout_appender.h#L76) and another in [ServiceServerLink](https://github.com/ros/ros_comm/blob/801b9c0e50f1a51913b48dcd688ae02420de7cc2/clients/roscpp/include/ros/service_server_link.h#L67). The C++ compiler is not enforced to inline the constructor and other member functions although they are defined in the header. Depending on the compiler, compile flags and optimization level it might decide for external linkage and hence only the symbol exported by the first compilation unit that uses it ends up in the final library and will be used by all other compilation units, too. The same applies even to other libraries linked into the process that also export `boost::condition_variable` symbols. In other words: It is pure luck which version of the constructor and `wait_for` member functions gets called and there is no guarantee that they are used consistently, because not all compilation units actually use and export all the member functions. 

   If this last assumption is correct, the problem only affects roscpp builds without any optimizations enabled (no `CMAKE_BUILD_TYPE` defined or `Debug` mode). Release builds are probably not affected because the calls into the backported `boost::condition_variable` class are inlined and no symbols are exported.

I think the only valid solution is to change the namespace of the backported condition variable implementation, e.g. to `boost_161::condition_variable`, to get rid of the link ambiguity. Unfortunately that might break ABI-compatibility because the type of a member variable changes, but because the memory layout stays the same it might work.

I will do further tests and propose a patch in the coming days.

**Comment by NickZ** [comment]
@meyerj excellent, thank you for this

**Comment by fujitatomoya** [comment]
@meyerj i do agree with the #3 assumption.

**Comment by ahoarau** [comment]
@meyerj did you finally fix this issue ?

**Comment by meyerj** [comment]
> @meyerj did you finally fix this issue ?

Yes, but my patch broke ROS timers and I did not have time yet to look into it again. But I could open a PR with the current patch, if someone else is interested.

**Comment by meyerj** [comment]
Non-working patch pushed to https://github.com/ros/ros_comm/compare/kinetic-devel...meyerj:fix-1343.

**Comment by meyerj** [comment]
Proposed patch submitted as #1557.
