### ISSUE TITLE
enable rostest to find unused rosmaster port  so that multiple test can run at the same time  (ros ticket #3826)

### ISSUE THREAD

**Issue by tfoote** [ros/ros_comm#141]
It would be nice if rostest is able to find unused rosmaster port if 22422 is used by another rostest process, so that multiple test can run at the same time. Currently we got following error.

  File "/opt/ros/electric/stacks/ros_comm/tools/roslaunch/src/roslaunch/launch.py", line 375, in _launch_master
      raise RLException("roscore cannot run as another roscore/master is already running. \nPlease kill other roscore/master processes before relaunching.\nThe ROS_MASTER_URI is %s"%(m.uri))

---

trac data:
- Owner: **kwc**
- Reporter: **k-okada**
- Reported at: **Sun Jan 29 23:24:32 2012**
- URL: https://code.ros.org/trac/ros/ticket/3826

**Comment by ahendrix** [comment]
I think the proper solution here is to have an option to allow the rosmaster bind an arbitrary port and then export that port number or master URI back to roslaunch.

This means that the OS will choose and assign an unused port automatically, rather than us worrying about race conditions caused by trying to find an open port and then bind it before another process does. It also eliminates any possibility of port collisions with other, non-ROS programs.

**Comment by trainman419** [comment]
I'm going to work on this because it promises an enormous speedup in my test system.

First notes:
- passing port 0 to rosmaster causes it to listen on a random port, as desired, but there is no output about which port it is listening on
- roslaunch runs the ros master in a separate process, so this will require some sort of mechanism to communicate the chosen port number back to roslaunch, after the master has been started

**Comment by dirk-thomas** [comment]
Implemented in #468.
