### ISSUE TITLE
Cannot run offboard node for mavros !

### ISSUE THREAD

**Issue by ziggBee30** [ros/ros_comm#1436]
Hi all
I am running a mavros_posix_sitl.launch https://dev.px4.io/en/simulation/ros_interface.html, 
and i have also created a package for an off board example for my drone (IRIS). i am able to run the node but itseens to have no connection with my gazebo. In my node i am already arming my copter and giving various info. The code can be found here : https://pastebin.com/mYP7QyS3
Please help me on what i am missing out here. 

something missing : 

ommands file: /home/zubair/Firmware/posix-configs/SITL/init/ekf2/iris
ERROR [Unknown] Error creating symlink /home/zubair/Firmware/ROMFS -> /home/zubair/.ros/ROMFS
Restoring terminal
process[gazebo-2]: started with pid [31245]
process[gazebo_gui-3]: started with pid [31250]
process[vehicle_spawn_zubair_HP_Pavilion_Notebook_31226_4351444113664537272-4]: started with pid [31255]
process[mavros-5]: started with pid [31256]
**[sitl-1] process has died [pid 31244, exit code 255, cmd /home/zubair/Firmware/build/posix_sitl_default/px4 /home/zubair/Firmware /home/zubair/Firmware/posix-configs/SITL/init/ekf2/iris __name:=sitl __log:=/home/zubair/.ros/log/ca4c3f4e-721d-11e8-afa0-10f00557463a/sitl-1.log].
log file: /home/zubair/.ros/log/ca4c3f4e-721d-11e8-afa0-10f00557463a/sitl-1*.log**
[ INFO] [1529236417.862022587]: FCU URL: udp://:14540@localhost:14557
[ INFO] [1529236417.865220370]: udp0: Bind address: 0.0.0.0:14540
[ INFO] [1529236417.865565054]: udp0: Remote address: 127.0.0.1:14557
[ INFO] [1529236417.866007418]: GCS bridge disabled
[ INFO] [1529236417.888115329]: Plugin 3dr_radio loaded
[ INFO] [1529236417.891666636]: Plugin 3dr_radio initialized

Thanks

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
