### ISSUE TITLE
I want call a service && I create a namesapce car{struct Request{};struct Response{}; Request request;}

### ISSUE THREAD

**Issue by loulansuiye** [ros/ros_comm#1495]

**Comment by loulansuiye** [comment]
::Request’ has no member named ‘serializationLength’
     return t.serializationLength();

**Comment by loulansuiye** [comment]
I do not create process in a ros workspace so I  do not know the name of node ,so how can I named the namespace ?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
