### ISSUE TITLE
ROS service with no/empty response is not supported by rospy client

### ISSUE THREAD

**Issue by yli-cpr** [ros/ros_comm#1500]
https://github.com/ros/ros_comm/blob/53d958fdccb15c2c5d7ed3cef33850e2f472f7d4/clients/rospy/src/rospy/impl/tcpros_service.py#L196

Why does it raise exception here?

**Comment by dirk-thomas** [comment]
Because a service handler is supposed to return the `response`. A service always has a response (even if it doesn't contain any data).

---

I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

**Comment by yli-cpr** [comment]
I probably referred to the wrong place of the code. But what I have seen is ROS srv with no response data didn't work when client makes calls. And the code I referred above seems on the server side. Sorry for that.

But if I see calling a ROS srv with no response data fails again, can I create an issue here?

**Comment by yli-cpr** [comment]
Actually the code I should post is here:

```
            responses = transport.receive_once()
            if len(responses) == 0:
                raise ServiceException("service [%s] returned no response"%self.resolved_name)
```

**Comment by maximeconnolly** [comment]
You are always supposed to return something in your service call. One of the reason you always want to send a response is to know if your service is hanging or not doing what it supposed to do. If you want to return nothing there is a standard srv for it http://docs.ros.org/api/std_srvs/html/srv/Empty.html or you could create your own srv definition with something similar. So this is not really a bug but more of a mild annoyance. I kinda want to rewrite the error message to something better.

**Comment by yli-cpr** [comment]
Never mind. I can't reproduce this any more. I met a problem like this a few months ago, and thought empty response service was just not supported until today. That's why I came here. But maybe something was wrong when I saw the problem, or something was fixed. Sorry for that.
