### ISSUE TITLE
rosbag error when I use the "rosbag record -O" command

### ISSUE THREAD

**Issue by Vincent1923** [ros/ros_comm#1501]
Hello!
I want to use the "rosbag record -O subset /scan" to record a bag file. But I have got the following error.
 
![qq 20180907172916](https://user-images.githubusercontent.com/32729558/45210948-92704c00-b2c3-11e8-9031-3fc20dc34dc2.png)

Could you please tell me the solution? Thank you!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Also don't post images but the textual content in order to be searchable.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
