### ISSUE TITLE
what is max freqency for a Publisher

### ISSUE THREAD

**Issue by hoppss** [ros/ros_comm#1657]
I try to use  a timer to trigger to publish a std_msg/Floot32 msg to test how much frequency that Publish could be.

     When the timer is set to 0.001, i use rostopic hz /pub to test frequency, result is 1000;

     when the timer is set to 0.0008, rostopic hz /pub , result is 1250;

     when the timer is set to 0.0005, rostopic hz /pub, result is only 1720;

     So I think the max frequency for a publisher is limited, The max frequency might be 1000 - 1500 hz

    I also  do more test.
   when i set timer's duration is 0.0001, this hz result is 4500-4700 only ...

**Comment by dirk-thomas** [comment]
A timer will still yield the cpu and it will be triggered "some time" after your specified duration. How long that time is depends on your system. If you want a kHz fir publishing I don't think you can / should use a timer - assuming you are not running a real time kernel.

---

I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

Anyway Anyway
