### ISSUE TITLE
 In publish raise ROSSerializationException(str(e))

### ISSUE THREAD

**Issue by elcingencturk** [ros/ros_comm#1691]
In my package that I created, there are 3 nodes currently. I also generate a custom message which is "AnchorScan". 

First node does some stuff and only publishes from `/IPS` topic.
Second node subscribes to the `/IPS` topic, takes the information, do some stuff and publishes another information from `/selectedAnchors` topic.

Until now everything works fine. But; 

Third node subscribes to the `/selectedAnchors` topic and does some calculations however does not publish anything from `/position` topic. 

After I run this command on terminal 

> rostopic echo /position

I received that kind of exception. 

I tried to change the queue size, rate etc. but nothing worked fine. 

All raised error is here: 
  ```
Traceback (most recent call last):

File /home/user/my_ws/src/my_pkg/src/pkg_name/3rd_node.py", line 366, in <module>
    position_pub_sub()
  File "/home/user/my_ws/src/my_pkg/src/pkg_name/3rd_node.py", line 324, in position_pub_sub
    pub.publish(msg)     
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: field x must be a list or tuple type
```
Thank you in advance for any help!!!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
