### ISSUE TITLE
Unable to run catkin_make

### ISSUE THREAD

**Issue by D-aggie** [ros/ros_comm#1749]
After downloading ros_comm into my workspace, I receive an error, 

|  Makefile:138: recipe for target 'all' failed make: * [all] Error 2 Invoking "make -j4 -l4" failed  |

when I run catkin_make_isolated

|    **/home/david/2catkin_ws/src/ros_comm/clients/roscpp/src/libros/service.cpp: In function ‘bool ros::service::waitForService(const string&, ros::Duration)’: /home/david/2catkin_ws/src/ros_comm/clients/roscpp/src/libros/service.cpp:92:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 const WallDuration wall_timeout{timeout.toSec()}; ^ /home/david/2catkin_ws/src/ros_comm/clients/roscpp/src/libros/service.cpp:92:50: error: in C++98 ‘wall_timeout’ must be initialized by constructor, not by ‘{...}’ const WallDuration wall_timeout{timeout.toSec()}; ^ CMakeFiles/roscpp.dir/build.make:1142: recipe for target 'CMakeFiles/roscpp.dir/src/libros/service.cpp.o' failed make[2]: * [CMakeFiles/roscpp.dir/src/libros/service.cpp.o] Error 1 CMakeFiles/Makefile2:766: recipe for target 'CMakeFiles/roscpp.dir/all' failed make[1]: [CMakeFiles/roscpp.dir/all] Error 2 Makefile:138: recipe for target 'all' failed make: ** [all] Error 2 <== Failed to process package 'roscpp': Command '['/home/david/2catkin_ws/devel_isolated/xmlrpcpp/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running: ==> cd /home**/david/2catkin_ws/build_isolated/roscpp && /home/david/2catkin_ws/devel_isolated/xmlrpcpp/env.sh make -j4 -l4

Command failed, exiting.**   |

And once I remove the package catkin_make still calls on the package

|    CMake Error at /home/david/2catkin_ws/devel/share/roscpp/cmake/roscppConfig.cmake:113 (message): Project 'roscpp' specifies '/home/david/2catkin_ws/src/ros_comm/clients/roscpp/include' as an include dir, which is not found. It does neither exist as an absolute directory nor in '/home/david/2catkin_ws/src/ros_comm/clients/roscpp//home/david/2catkin_ws/src/ros_comm/clients/roscpp/include'. Check the website 'http://ros.org/wiki/roscpp' for information and consider reporting the problem. Call Stack (most recent call first): /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package) beginner_tutorials/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred! See also "/home/david/2catkin_ws/build/CMakeFiles/CMakeOutput.log". See also "/home/david/2catkin_ws/build/CMakeFiles/CMakeError.log". Invoking "cmake" failed   |

Any help would be appreciated, thanks!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
