### ISSUE TITLE
Publishing message immediately after topic creation with rospy is never sent. 

### ISSUE THREAD

**Issue by ghost** [ros/ros_comm#176]
Hi all,

After attempting to set the IP address of a bot on boot, I have run into an issue where the initial messages are never sent. Running 'rostopic echo "/TestTopic"' prior to the following code, I only receive 'Message 2'. Sleeping before message 1 also works. 

[code]
import socket
import time
import std_msgs
import rospy
rospy.init_node("TestNode")
pub = rospy.Publisher("/TestTopic", std_msgs.msg.String)
pub.publish("Message 0")
time.sleep(1)
pub.publish("Message 1")
[/code]

The issue is easily solved in my situation, but may be problematic in situations other than mine, and the solution is not exactly optimal..

**Comment by dirk-thomas** [comment]
This is a fundamental design choice of ROS and not "fixable". The connections between nodes happens after each node is started so messages can get lost until all these connections are made.

You should design your nodes in a way that they either do not rely on each message to arrive or consider using latched topics to at least get the last message when the connections is established after it was initially published.

**Comment by ghost** [comment]
I don't think you understand the issue.. We are using an Arduino with Rosserial to subscribe to a topic 'LCD' which we are sending the systems IP address on boot, the LCD is listening to a topic, then the python script starts, firing a message in code very similar to that above - the subscriber is already subscribed to the network prior to the publisher being created and sending a message, but no message is received.

**Comment by dirk-thomas** [comment]
I think I do understand your scenario pretty well.

The problem is that the subscriber is only "announcing" to the rosmaster that he wants to subscribe to the topic, it is not directly subscribing to the topic. Then you start the publisher which "announces" to the rosmaster that he wants to publish to the topic. At that point in time there is not yet any connection established between the publisher and the subscriber therefore the first messages vanish.
Asynchronously the subscriber will now get notified by the master about the new publisher and then initiates a direct connection between the publisher and the subscriber. And only after this direct connection has been established the subscriber will receive the published message.

You will find the similar questions on answers.ros.org which boil down to the same source:
- http://answers.ros.org/question/34264/messages-lost-in-ros-electric/
- http://answers.ros.org/question/11167/how-do-i-publish-exactly-one-message/
- http://answers.ros.org/question/12655/publish-initial-pose/

**Comment by clacarbone** [comment]
Dirk Thomas notifications@github.com wrote:

> This is a fundamental design choice of ROS and not "fixable". The
> connections between nodes happens after each node is started so
> messages can get lost until all these connections are made.

Dirk I hit this same wall myself, coming to rely on delays to wait for the connections to choke up, but that is definitely not deterministic.

One thing I would like to see is a member (of both publisher and subscriber classes) to tell if the connection is established.
Bool ROS::subscriber.isestablished(topic)
Bool ROS::publisher.isestablished(topic)

That would be nice.
I don't see me having the time to attempt that in the near future but just for reference: would you mind pointing at the resources and modules I would need to tap into to make those members available?

Thanks
Claudio
-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by dirk-thomas** [comment]
The approach you describe is not possible. A publisher has separate connections to each subscriber. An by definition in a publish/subscribe system the publisher is decoupled from the subscriber so he does not know how many subscribers should be there.

You can already check the number of current connections for a publisher and subscriber (`get_num_connections()`) but adding such logic into your nodes makes them less flexible and reusable.
