### ISSUE TITLE
Is ros::Rate accelarate with faster than real time clock?

### ISSUE THREAD

**Issue by gajena** [ros/ros_comm#1799]

**Comment by cwecht** [comment]
Could you elaborate more on your question?

**Comment by gajena** [comment]
Like if I set `ros::Duration(t).sleep()` and increase the speed of `/clock` then will the sleep time become less(with respect to real time)?

**Comment by cwecht** [comment]
Yes it does, but the accelaration is limited due to a hard-coded 100ms sleep: https://github.com/ros/roscpp_core/blob/d2bb8cbcfd4944e48d16cdb20edfab5d225db265/rostime/src/time.cpp#L479

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
