### ISSUE TITLE
Misnomer in rospy tutorial

### ISSUE THREAD

**Issue by DanielHeise** [ros/ros_comm#1801]
When reviewing the **catkin** tutorial information for _Setting Up Your PYTHONPATH_ a reference in _"1. Example"_ calls out **rosbuild** instead of catkin; see attached image.

**Page Reference:**
[rospy_tutorials::PythonPath](http://wiki.ros.org/rospy_tutorials/Tutorials/PythonPath#line-16-3)

**Excerpt:**
`For rosbuild we create a new package in our source folder:`

**Screenshot:**
![image](https://user-images.githubusercontent.com/35785522/64255238-f2a5c800-ceee-11e9-8479-bb11a4f92cda.png)

**Comment by dirk-thomas** [comment]
Thank you for the report. I have fixed the content in http://wiki.ros.org/action/diff/rospy_tutorials/Tutorials/PythonPath?action=diff&rev1=26&rev2=27.

In the future please consider to update the wiki content directly - it is intentionally publically editable by the community so that everyone can contribute.
