### ISSUE TITLE
ROS Catvehicle error. 

### ISSUE THREAD

**Issue by arashMarashian** [ros/ros_comm#1828]
Hi everyone, I was testing one of the examples of **Catvehicle** toolbox that is presented at [https://cps-vo.org/node/26603](url) and when I run the following code:
`roslaunch catvehicle catvehicle_neighborhood.launch
`
I get these errors:

> ERROR: cannot launch node of type [cmdvel2gazebo/cmdvel2gazebo_node]: cmdvel2gazebo
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/arash/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share

What is wrong and what should I do?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
