### ISSUE TITLE
ROS in ev3

### ISSUE THREAD

**Issue by AnushRobotics** [ros/ros_comm#1905]
how to install ros in ev3dev
we have some problem in installing Docker in ev3dev
when we try using this _command_
$ sudo apt-get install docker-ce
we often get errors like
E: Unable to locate package docker-ce

pls help with any alternate ideas
pls help who knows the solution

**Comment by cwecht** [comment]
This seems to be an issue with ev3 ratther than with ros_comm. Please consider to ask here: https://github.com/ev3dev/ev3dev/issues

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
