### ISSUE TITLE
How to set simulation time interval on RViz and Gazebo

### ISSUE THREAD

**Issue by MatteoL95** [ros/ros_comm#1938]
Hi everyone, I'm new to ROS and I'm building a simulation python script for my thesis project.
I have to command a movement via ROS and MoveIt! in RViz and Gazebo and the simulation time must be in the interval T = [0, 3] sec (therefore start_time = 0s and end_time = 3s).
I would like to know how to set the start_time to 0 when I start the movement (and not before) and make the simulation and therefore the movement end within 3sec from start_time.
I hope I have been understandable and I hope I have exposed the question well.

My current configuration is:
- ROS Melodic
- Gazebo 9
- Ubuntu 18.04 LTS

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
