### ISSUE TITLE
Could not find library corresponding to plugin rosbag/NoEncryptor

### ISSUE THREAD

**Issue by bfeng1** [ros/ros_comm#1988]
Hi all,

I am currently learning how to use rosbag, but when I run the command "rosbag play D:\summer_project\20200619_123634.bag", I got the following error:
```
C:\Windows\System32>rosbag play D:\summer_project\20200619_123634.bag
[ INFO] [1593471808.789562700]: Opening D:\summer_project\20200619_123634.bag
[FATAL] [1593471809.093414800]: Could not find library corresponding to plugin rosbag/NoEncryptor. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```
I did some research online and I need to do something with the NoEncryptor. Here is the link I found: http://wiki.ros.org/pluginlib;
https://docs.ros.org/melodic/api/rosbag_storage/html/c++/classrosbag_1_1NoEncryptor.html;

 I have never use c language, so i got no clue for the setup process. What do I need to do with the .cpp file and .h file? If anyone could give me some ideas or suggestions, that would be highly appreciated!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
