### ISSUE TITLE
How to load a rosbag which is in s3 bucket?

### ISSUE THREAD

**Issue by Sowjanya06** [ros/ros_comm#1990]
I have massive rosbag files in the s3 bucket. Instead of downloading those bag files, I want to access it through the python script and do my stuff like reading the topics, their msg types.
https://gist.github.com/ptsurko/a64f980fed8ad433f10eccf64f1cfad9l
I have tried with the above snippet, but it didn't work. I would be grateful, if anybody has any pointers towards this.
The question was also asked in the ros answers, This is the link
https://answers.ros.org/question/356555/how-do-i-access-ros-bag-file-from-s3-bucket-in-python/

**Comment by mikepurvis** [comment]
I can't read the linked gist, but you would need some kind of s3-specific bag reader/streamer, which could use S3-specific APIs to seek through the file (or that could use the HTTP Range header, which S3 supports).

Alternatively, it's possible this could work with the various solutions that mount an S3 bucket natively, but you'd have to check that you really were only getting on-demand accesses. I deal with bags in the 1-2GB range fairly regularly, and do experience long startup times before the first messages come out, but I haven't yet looked into what exactly is going on under the hood; note that my bags are compressed and encrypted, but both those operations are done per-block so in theory should not affect startup time.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
