### ISSUE TITLE
how many cases the error “new node registered with same name” will be reported?

### ISSUE THREAD

**Issue by shike15** [ros/ros_comm#2028]
https://github.com/ros/ros_comm/blob/3d137ca91109a9f229d0701e618758ef7f817218/tools/rosmaster/src/rosmaster/registrations.py#L467

- Configuration
   - ROS kinetic
   - Ubuntu 16.04

- Issue details

When I start all ros nodes of my robotic system, sometimes I will see the "new node" error in one node's log, for example:

```bash
[ WARN] [1598342227.977271227]: Shutdown request received.
[ WARN] [1598342227.977317667]: Reason given for shutdown: [new node registered with same name]
```

I am sure that there are no nodes with the same name, because the error does not appear each time.

And, I have modify the source coude above, just add log to debug this issue，the codes are below:
            
```python
            if node_ref.api == caller_api:
                return node_ref, False
            else:
                self.logger.warn("new node registered with same name: [%s, %s] => [%s, %s]",
                                 node_ref.id, node_ref.api, caller_id, caller_api)
                bumped_api = node_ref.api
                self.thread_pool.queue_task(bumped_api, shutdown_node_task,
                                            (bumped_api, caller_id, "new node registered with same name"))
```

When I meet this error again after the log has benn added, I check the master log, but I can not find the log I have added, so maybe the error is not sent from here.

So, I want to ask for help, except here, is there any other cases the error “new node registered with same name” will be sent or reported?

Thanks a lot!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
