### ISSUE TITLE
Can only receive several start message 

### ISSUE THREAD

**Issue by oym1994** [ros/ros_comm#2031]
Hi,
I wrote a ROS package and come across a strange issue. The listener node can receive 3~6 message at the beginning and then it received nothing. And I can see the message in the terminal. Is there anyone who knows the reason and how to solve it?
Platform : Ubuntu 18.04, ROS melodic,  intel NUC-10
Thank you!

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
