### ISSUE TITLE
Probelm Ros Kinetic 1.12.16

### ISSUE THREAD

**Issue by FlavioLopes90** [ros/ros_comm#2041]
Hello,

With the new update of ROS kinetic 1.12.16 

We obtain always the same error when using comunication with diferents nodes.
"Failed to contact master at [localhost:11311].  Retrying...::connect error = 99
.::connect error = 99
.::connect error = 99
.::connect error = 99
"
We already using this code since a year ago with version 1.12.14, and never have this problem.. Any ideia of the issue? @dirk-thomas 

Thanks in advance

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
