### ISSUE TITLE
Sourcing setup.bash before RosLaunchParent

### ISSUE THREAD

**Issue by byteofprash** [ros/ros_comm#2047]
**My setup:**
I have a docker container with ROS Melodic and cartographer installed in it. 

* When I source the setup.bash I can find all the packages installed such cartographer_ros and hence I can do a roslaunch with my launch file.
* I change the parameters of a lua file (which is read by the launch file) to run cartographer with different parameters.
* The changed parameters are reflected when I source my setup.bash of my workspace again.
So everything works fine from the terminal

* I have a python webapp running in the same container, where I receive the parameters and run the launch file through the python API.
How I run my launch file:
```
mylaunch = roslaunch.parent.ROSLaunchParent(uuid, roslaunch_file, force_log=True)
mylaunch.start()
```

**My Issue:**
1. Calling a `subprocess.call('/bin/bash /catkin_ws/install/setup.bash')` to source the setup.bash wouldn't reflect the changes in my running python webapp.
2. Is there a python api to load the env? 
3. What is the way to make my app to know the changes that happened in the workspace?

Sorry if this more of a question rather than an issue. But I can't seem to achieve a pure python implementation of this. 
Please let me know if this is already achievable in some way. If it's not documented I'm happy to volunteer to document this too..

Thanks for your time.

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
