### ISSUE TITLE
rosbag with roslz4: Conda version mismatch

### ISSUE THREAD

**Issue by balbok0** [ros/ros_comm#2218]
Hi,

I've been trying to install rosbag in conda environment and read a bag with lz4. However, when using [rosbag conda-forge package](https://anaconda.org/conda-forge/ros-rosbag), it requires `python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']`, which does not include 3.9.

At the same time, [ros-roslz4](https://anaconda.org/conda-forge/ros-roslz4) dependency does specifically look for python 3.9, and otherwise throws an error `ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory` during import.

The combination of two makes it impossible to create a fully conda based enviornment in which reading lz4 bags is possible.

**Comment by Se6T** [comment]
Hello, 
I have had a similar problem. 
roslz4 uses lz4, which means it can be fixed by a few easy steps:

1) instead of roslz4, import lz4 and lz4.frame
2) add a new function:
`def decompress(self, data):`
 `    decompressor = lz4.frame.LZ4FrameDecompressor()`
`    output = decompressor.decompress(data)`
`    return output`
3) remove `found_lz4`: from `elif chunk_header.compression == Compression.LZ4` in seek_and_read_message..
4) instead of `roslz4.decompress` use `self.decompress`

Hope this helps, 
Seb
