### ISSUE TITLE
Subscriber node changes the topic to which it listens

### ISSUE THREAD

**Issue by blaroche** [ros/ros_comm#24]
This defect is based on this question: http://answers.ros.org/question/48086/problem-with-subscribing-to-a-topic-that-contains-slash

I have a node that subscribes to /parent/child, which is an unadvertised topic. Then, a publisher comes in on /parent. The node subscriber automagically starts listening to /parent instead of /parent/child.

**Comment by dirk-thomas** [comment]
I can not reproduce the described behavior - I tried the following:

Running a simple subscriber on /foo/data (note: data is actually a field of the String message published on /foo later):
`#!/usr/bin/env python
import rospy
from std_msgs.msg import String
def callback(data):
    rospy.loginfo(rospy.get_caller_id() + 'Incoming message: %s',data.data)
rospy.init_node('listener', anonymous=True)
rospy.Subscriber('/foo/data', String, callback)
rospy.spin()`

Publish message on the parent topic:
`rostopic pub -r 2 /foo std_msgs/String text`

And the subscriber does not receive/output any messages.
`rostopic info /foo` and `rostopic info /foo/data` shows that both endpoints are clearly separated and publishing/listening on different topics:
```Type: std_msgs/String
Publishers: 
- /rostopic_7493_1353507454648 (http://localhost:60573/)
  Subscribers: None`
  and
  `Type: std_msgs/String
  Publishers: None
  Subscribers: 
- /listener_7483_1353507449360 (http://localhost:39999/)```

Can you please try to reproduce the issue with this command sequence?

For `rostopic echo` the behavior is intended that the subscriber tries to extract the fields from parent topics.

**Comment by blaroche** [comment]
I'm on a business trip so I won't be able to try it for a while. :-(

Have you tried the C++ example that I wrote in the original question? Do you see the behavior there or not?

**Comment by dirk-thomas** [comment]
You used `rostopic` for subscribing to the topic which has a different semantic as mentioned in the answers. rostopic "magically" subscribes to the parent topic to extract field from these messages. That is intended and documented behavior.

A "real" node does not behave like that - it will stick to the specific topic name. I verified that with a Python subscriber node and confirmed that it works in that scenario as expected.

So the subject of this issue would be more accurate with "rostopic changes the topic to which it listens" since that behavior does not appear for normal nodes.
