### ISSUE TITLE
rosbag: feature request: record service calls

### ISSUE THREAD

**Issue by jianghengle** [ros/ros_comm#250]
When debugging ros programs, except for messages we also want to check the service calls, which should include the caller name, the server name, request and response messages. However, rosbag currently does not record service calls. Could we add this feature into rosbag in the future?

**Comment by dirk-thomas** [comment]
This feature is not likely to be implemented.

The rational is that services are fundamentally different than topics. Topics can be easily recorded by rosbag since they are essentially a message bus which arbitrary subscribers can register for. Services on the other hand are only handled by a specific node so rosbag has no way of intercepting the communication and recording it.

**Comment by lgeo3** [comment]
As an alternative solution, do you recommend to publish the aforementioned information (response, request, caller, etc..) using an associated publisher, if the service need to be monitored?

**Comment by dirk-thomas** [comment]
I don't have a good recommendation for this problem. Yes, you could extend every service to publish incoming requests and outgoing responses somehow which would at least allow to introspect what happened.
