### ISSUE TITLE
roslaunch tab: do not show files with a particular prefix or inside a particular subdirectory

### ISSUE THREAD

**Issue by corot** [ros/ros_comm#254]
Rename launch files as xml or something else is a good idea, but... would not be better to ignore, for example, all launch files inside "include" directories? Or all that start with "_"? Or whatever other convention. Like this we keep the semantics of the .launch extension.

**Comment by bit-pirate** [comment]
+1

What do the core ROS devs think about this?

**Comment by dirk-thomas** [comment]
There is no convention in ROS where to put files within a package. These are only recommendations. So requiring launch files to be in a certain subfolder will very likely break existing code. Establishing conventions might be a good idea but can likely only be put in place with a major version of ROS.

The `.launch` extension makes it pretty clear what these files are. Why should they be renamed into `.xml` in the first place?

**Comment by bit-pirate** [comment]
I agree that we should not impose a convention like putting everything to be included in a include folder.

Regarding the renaming of specific launchers from `.launch` to `.xml`, we copied that from PR2 folders, which hold a big amount of launchers. If someone uses roslaunch's tab completion on such a folder, he will see an overwhelming list of launchers. For beginners it's hard to figure out, which launchers can be used directly and which ones are used only as includes.

For TurtleBot, we also have a significant amount of launchers, which are need to handle TB 1&2. To make it easier for users we plan to rename the launchers intended to be used only as includes to `.xml` in order to hide them from the tab completion.

However, since the `.xml` ending removes important meaning, i.e. it's a xml file for roslaunch, we would prefer to keep the `.launch` ending and instead add an underscore or similar.

**Comment by dirk-thomas** [comment]
An alternative would be naming the files which should not be launch from the console with a suffix `.launch.xml`. That would hide it from the completion but still keep the semantic obvious.

**Comment by bit-pirate** [comment]
True, that would be a simple solution and superior to just `.xml`. However, an underscore suffix would be cleaner, no?

**Comment by tfoote** [comment]
I'd prefer .launch.xml to suppress the autocomplete.  A trailing underscore
is unpronouncable and would make differentiating files quickly in a file
list very hard as it's one small character different.

**Comment by dirk-thomas** [comment]
The proposed suffix `.launch.xml` achieves the goal of not showing the files in completion of roslaunch while maintain the semantic meaning of being a launch file. Since this "solves" the request without changing any code we won't implement any special handling like underscore suffix etc.

**Comment by bit-pirate** [comment]
I'm happy with this approach as well.
