### ISSUE TITLE
rxgraph is not refreshed properly when a publisher shuts down

### ISSUE THREAD

**Issue by blaroche** [ros/ros_comm#255]
rxgraph is not refreshed properly when a publisher shuts down but the node handle stays alive. More exactly, the arrow in the graph stays, but the list of topics (in the right pane) is updated properly.

To reproduce, create a node with a publisher, create another node with a subscriber, observe the connection in rxgraph, then call shutdown on the publisher while leaving the node running, and finally observe that the two nodes are still shown as connected.

The original question: http://answers.ros.org/question/50271/rxgraph-is-not-refreshed-properly-when-a-publisher-shuts-down/

**Comment by dirk-thomas** [comment]
rxgraph is not part of this repository but https://github.com/ros-visualization/rx. Therefor I will close this ticket - please feel free to open a ticket in the rx repository.

But since all rx tools are deprecated and with http://ros.org/wiki/rqt_graph a replacement already exists it is not likely that the issue will get fixed without a community provided patch. You might want to give rqt_graph a try and see if it already solves your issue.
