### ISSUE TITLE
Allow empty machine attribute

### ISSUE THREAD

**Issue by liborw** [ros/ros_comm#274]
Allowing empty machine attribute of node tag would help to make a launch-files with optional machine argument.

An example:

```
<arg name="machine" default=""/>
<node name="some_name" pkg="some_pkg" type="some_type" machine="$(arg machine)"/>
```

**Comment by dirk-thomas** [comment]
Wouldn't it be sufficient if you use `localhost` / `127.0.0.1`?

**Comment by liborw** [comment]
It would, but it require to have defined localhost as a machine in every such launchfile.

**Comment by liborw** [comment]
I still think that allow machine to be empty would be the better solution.

This is what you are suggesting?

```
<machine name="localhost" address="localhost" env-loader="/opt/ros/hydro/env.sh"/>
<arg name="machine" default="localhost"/>
<node name="some_name" pkg="some_pkg" type="some_type" machine="$(arg machine)"/>
```

**Comment by dirk-thomas** [comment]
None of the attributes in roslaunch currently supports this kind of behavior. In order to stay consistent that rule would need to apply to all attributes (e.g. `ns` attribute of the `group` tag).

This would require some effort to investigate the effect on all attributes and describing the consequences of such a change. Since the maintainers do not have the time to address this in the near future the issue will be marked with the milestone _untargeted_.

Any contribution on this is highly welcome.

**Comment by furushchev** [comment]
@dirk-thomas @liborw I've got the same issue.
How about to take `localhost` as a type of reserved word, and if node are written in launch files with `machine="localhost"`, launch the node even if there is no declaration of `<machine name="localhost" address="localhost" />`?

**Comment by dirk-thomas** [comment]
In the meantime some attributes started to allow empty values (e.g. the include tag #882). So allowing an empty machine tag doesn't sound that different anymore. A generic approach (optional attributes with an empty value are considered equal to the attribute not being specified) would be preferred. But any pull request would be appreciated. Also if it only implements the handling of an empty machine tag.

**Comment by peci1** [comment]
Solution proposed in #1885.
