### ISSUE TITLE
ros_comm depends on non-existent package test_ros

### ISSUE THREAD

**Issue by wmeeusse** [ros/ros_comm#39]
The test_rosservice packages in ros_comm has a dependency on test_ros, but this dependency does not exist anywhere.  This causes devel builds and prerelease builds like this one to fail: http://jenkins.willowgarage.com:8080/job/devel-groovy-ros_comm/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/29/console. 

As one of the tasks of the devel and prerelease builds is to find out if the dependencies of a repository are correct, it's not a good idea to simply ignore this incorrect dependency.

**Comment by dirk-thomas** [comment]
There is no way to declare these packages in the rosdistro file because that would "release" these package, creating debian packages for them and making them publicly available.

Please modify the script running the devel jobs on the farm to "accept" packages which are part of the repository which is being tested. For bloom it is exactly the same situation when trying to release a repository like ros_comm and it has therefore been modified the same way.

Update: I misread the name of the dependency - found that wrongly name dependency in test_rosservice. Will be fixed soon.

**Comment by wmeeusse** [comment]
Please don't close tickets before they are resolved.

The test packages in the ros_comm repository do not need to get installed, that's not the problem. The devel/prerelease tools are already built to deal with a repository that has a different set of packages than what the rosdistro file describes.  That's how you can release a new repository, or add/remove packages from a repository.

The problem here is that the dependencies of the test packages are missing. In this case, there's a test package that depends on test_ros, which is not declared anywhere. So the solution is not to release the test packages in ros_com, but to release the dependencies of the test packages in ros_comm.
