### ISSUE TITLE
Ros time sliently casts float times after 2038 to invalid secs/nsecs values

### ISSUE THREAD

**Issue by cdellin** [ros/ros_comm#425]
The ROS time constructors/etc that accept float secs arguments cast them to uint32, but don't check whether they're far into the future (so that they can't be represented correctly).  Perhaps it should throw an exception?

Also, the wiki on messages [0] asserts that the secs/nsecs fields are stored as signed 32-bit ints, but are they not serialized as unsigned values?

[0] http://wiki.ros.org/msg

**Comment by dirk-thomas** [comment]
The content on the wiki page was actually wrong since it was written in 2009. The `Time` objects is using unsigned 32bit ints (and is also serialzed as such). I have updated the page accordingly: http://wiki.ros.org/action/diff/msg?action=diff&rev1=42&rev2=43 

Regarding the out-of-range conversion: usually in C++ neither overflows nor underflows result in exceptions. If you would like to add this to that specific conversion function please consider to contribute a PR adding the necessary checks and exceptions.

**Comment by cwecht** [comment]
I think, this issue can be closed. The conversion from float/double to `ros::Time` is checked now. ros/roscpp_core#105 still exists, but this is beyond this issue.
