### ISSUE TITLE
rospy docs for Hydro are missing

### ISSUE THREAD

**Issue by mikepurvis** [ros/ros_comm#471]
Code API link here: http://wiki.ros.org/rospy

Points here: http://docs.ros.org/hydro/api/rospy/html/

Non-rosdistro link also affected: http://docs.ros.org/api/rospy/html/

**Comment by dirk-thomas** [comment]
It looks like `catkin_basic` is once again screwing the job: http://jenkins.ros.org/view/Hdoc/job/doc-hydro-ros_comm
I can't repeat often enough how bad `catin_basic` is... :angry: 
I will try to look into it but it could be that this is not an easy fix (without throwing catkin_basic out of the pipeline).

**Comment by dirk-thomas** [comment]
When the doc job for Hydro ros_comm is running it find rosgraph_msgs installed on the system: http://jenkins.ros.org/view/Hdoc/job/doc-hydro-ros_comm/210/console (search for `find_package(rosgraph_msgs) found: /opt/ros/hydro/share/rosgraph_msgs/cmake`).

catkin_basic can't deal with it since it blindly includes the msgs CMake file of the package which results in duplicate target names (search for `CMake Error`).

The question of the day remains: why does the doc job installs `ros-hydro-rosgraph-msgs` in the first place?

**Comment by dirk-thomas** [comment]
Fixed with https://github.com/ros-infrastructure/jenkins_scripts/commit/e6ef8a036554f39577332b06e203b2ef46eb82fd

(Please don't judge me by the content of the patch :wink:)
