### ISSUE TITLE
roslaunch: Should run_depend on rostest?

### ISSUE THREAD

**Issue by mikepurvis** [ros/ros_comm#475]
The roslaunch-check script imports a helper module from rostest:

https://github.com/ros/ros_comm/blob/indigo-devel/tools/roslaunch/scripts/roslaunch-check#L96

Example failure:

http://jenkins.ros.org/job/devel-indigo-teleop_twist_joy/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/1/console

Seems we could just document that if you're build-depending on roslaunch for the sake of `roslaunch_add_file_check`, you need to also test-depend on rostest. But the "right" solution would be for roslaunch to itself run_depend on rostest.

**Comment by dirk-thomas** [comment]
`roslaunch` can not depend on `rostest`. The dependency is the other way around: `rostest` depends on `roslaunch`.

But the referenced code part only uses the following three symbols:
- `rostest.rostestutil.xmlResultsFile` (https://github.com/ros/ros_comm/blob/41e7df0db406c55c09c970ae7a09b21b2751bcfd/tools/roslaunch/scripts/roslaunch-check#L103)
- `rostest.rostestutil.test_failure_junit_xml` (https://github.com/ros/ros_comm/blob/41e7df0db406c55c09c970ae7a09b21b2751bcfd/tools/roslaunch/scripts/roslaunch-check#L116)
- `rostest.rostestutil.test_success_junit_xml` (https://github.com/ros/ros_comm/blob/41e7df0db406c55c09c970ae7a09b21b2751bcfd/tools/roslaunch/scripts/roslaunch-check#L122)

Those are actually only redirects to rosunit: https://github.com/ros/ros_comm/blob/41e7df0db406c55c09c970ae7a09b21b2751bcfd/tools/rostest/src/rostest/rostestutil.py#L79-L81

Since `roslaunch` can safely add a dependency on `rosunit` it should use those symbols instead. Please try #476 and check if it solves the issue.

**Comment by mikepurvis** [comment]
Okay, yes, that works for me. Sorry for the delay!
