### ISSUE TITLE
rospy.sleep(): request for specific exception if time moved backwards

### ISSUE THREAD

**Issue by jowave** [ros/ros_comm#485]
I kindly request for the TODO of rospy.sleep() in [rospy.timer.py](https://github.com/ros/ros_comm/blob/hydro-devel/clients/rospy/src/rospy/timer.py) to be implemented and use a specific exception if ros time moved backwards.
I had trouble to find the cause of a python node shutting down, when using 'rosbag play -l --clock bagfile'. When the implementation follows the ros tutorials on python the ROSInterruptException is always catched:

``` python
if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException: pass
```

And there is no error message telling you, that time moved backwards.

**Comment by dirk-thomas** [comment]
Since it is not very likely that this will get implemented by the maintainer I have marked the issue with the milestone `untargeted`.

Please consider to provide a pull request for the proposed feature. One comment though: a newly introduced exception would anyway need to inherit from `rospy.ROSInterruptException` in order to not change the API in terms of raising a new unrelated exception.

**Comment by jowave** [comment]
I made pull request #491 for the proposed feature. In addition to the exception inheriting from rospy.ROSInterruptException a logerr message is produced to inform the user. I hope this is ok. I looked into [rospy.topics.py](https://github.com/ros/ros_comm/blob/hydro-devel/clients/rospy/src/rospy/topics.py) which produces log messages, too.
