### ISSUE TITLE
rospy: console output formatting using ROSCONSOLE_FORMAT

### ISSUE THREAD

**Issue by mjyc** [ros/ros_comm#517]
ROS C++ has [a feature](http://wiki.ros.org/rosconsole#Console_Output_Formatting) that controls output formatting using ROSCONSOLE_FORMAT environment variable. However, it seems like this feature is not in rospy and [this issue](https://github.com/osrf/capabilities/issues/24) shows possible update on rospy to provide the feature.

Is this feature still being considered to be implemented in rospy?
If not, I'm interested in implementing this feature myself & make PR, however, rospy seems quite complex and not sure where to implement this functionality. Any guidelines & suggestion to implement this would be very helpful.

**Comment by dirk-thomas** [comment]
It is not planned to add this feature to rospy (hence there is no open ticket for yet). Please feel free to look into it but consider that any patch which requires changing API / default behavior will likely only be applied for future ROS versions.

`rospy` uses the Python `logging` package to handle most of the logging logic. You can find the entry points for logging in the `rospy.core` module: https://github.com/ros/ros_comm/blob/fab4840ef79f5334bcd043e057a1909183842159/clients/rospy/src/rospy/core.py#L119

I will mark this ticket with the milestone `untargeted` since the maintainers are not likely not spend any time on this feature.

**Comment by wjwwood** [comment]
Reference: https://github.com/osrf/capabilities/issues/24

**Comment by dirk-thomas** [comment]
The corresponding PR has been merged and released. Thanks!
