### ISSUE TITLE
roslz4 import problem after building from source

### ISSUE THREAD

**Issue by anuraj-rp** [ros/ros_comm#528]
Hi,

I built ros_comm from source. 
After running roscore, when I run rostopic. I get the error
No module named _roslz4

I edited the file 
/opt/ros/indigo/lib64/python2.7/site-packages/roslz4/--init--.py
to remove the underscore before the name _roslz4 to make it 
from roslz4 import \* 
and now it works fine.
Seems like a small bug.

**Comment by dirk-thomas** [comment]
The underscore is not a bug. It imports the symbols from the shared library with the name `_roslz4`.

Without an underscore the symbols `roslz4.LZ4Compressor` and `roslz4.LZ4Decompressor` are not available anymore.

**Comment by dirk-thomas** [comment]
Please describe what exactly you tried to do in order to help identify the problem in your local build.

After building from source you should have the shared library in `devel/lib/python2.7/dist-packages/roslz4/_roslz4.so`. And when sourcing the setup file from the devel folder that should be importable from within Python.

**Comment by anuraj-rp** [comment]
Hi,
Thanks for the help. 
I only had /devel/lib64 on the PYTHANPATH. I added/ /devel/lib to the PYTHONPATH and now it works. 
Thanks again.
