### ISSUE TITLE
unregister() method to message_filter.Subscriber on python

### ISSUE THREAD

**Issue by wkentaro** [ros/ros_comm#681]
Do you have plan to implement this?
Or there is other way to achieve this?

**Comment by dirk-thomas** [comment]
There is no plan for feature development in this repository (see the status in the rosdistro: https://github.com/ros/rosdistro/blob/00524f6409253449fdba6ee595236cd85f476ab3/jade/distribution.yaml#L3128).

Since the `rospy.Subscriber` is accessible as a member variable `sub` have you tried to call its `unregister()` method?

**Comment by wkentaro** [comment]
Yeah, that works. But `message_filters.Subscriber.unregister()` is more natural, isn't it?
message_filter for cpp has that method.

**Comment by wjwwood** [comment]
So it's just `message_filters.sub.unregister()` versus `message_filters.Subscriber.unregister()`? If you propose a pull request with what you think is a better API, then we'll consider it, but changes to the public API will likely be delayed until Kinetic.

**Comment by wkentaro** [comment]
I'm thinking add just one method.
https://github.com/ros/ros_comm/pull/683
