### ISSUE TITLE
rospy service DeserializationError based upon unrelated object in callstack

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [ros/ros_comm#856]
Four main use cases:
   1) A service that has the same message class somewhere in both the request and the response
   2) A service that has a message class in the request, then another service is called with that message class in the response
   3) Same as #2, but service with response first
   4) Call a service, but instantiate the message class that occurs in the response anywhere on the callstack.  

If any of these four cases occur (I can probably come up with more), then either the Service or the ServiceProxy crashes with the following callstack:

```
Traceback (most recent call last):
  File "/home/enelson/Work/rospy_service_bug/src/rospy_service_bug/src/service_proxy.py", line 97, in <module>
    main()
  File "/home/enelson/Work/rospy_service_bug/src/rospy_service_bug/src/service_proxy.py", line 93, in main
    fail_case_4()
  File "/home/enelson/Work/rospy_service_bug/src/rospy_service_bug/src/service_proxy.py", line 79, in fail_case_4
    bn.response()
  File "/home/enelson/Work/rospy_service_bug/src/rospy_service_bug/src/service_proxy.py", line 42, in response
    retval = self._service_response("benign request")
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: receive_once[/service_response]: DeserializationError cannot deserialize: 'CustomMessage' object attribute 'custom_field' is read-only

```

Bug occurs in both Indigo and Kinetic. 

Reproducible test case in github: 
    https://github.com/TinyTheBrontosaurus/rospy_service_bug
Directions for test case:
- clone
- call catkin_make
- call any of the top-level shell scripts, which will fail. 

The workaround is not to reuse message types; which can get tedious. 

A related question on ROS Answers: 
http://answers.ros.org/question/218216/rossrv-cannot-deserialize-custom-msg/

**Comment by dirk-thomas** [comment]
After trying your test case I doubt that the problem is actually in ROS. You seem to be using the message types / instance incorrectly. In various locations you are using the message **type** instead of creating a message **instance**:
- https://github.com/TinyTheBrontosaurus/rospy_service_bug/blob/4338f11662717d38fc63543987502d7d6c6fb4da/src/rospy_service_bug/src/service.py#L10
- https://github.com/TinyTheBrontosaurus/rospy_service_bug/blob/4338f11662717d38fc63543987502d7d6c6fb4da/src/rospy_service_bug/src/service_proxy.py#L24
- https://github.com/TinyTheBrontosaurus/rospy_service_bug/blob/4338f11662717d38fc63543987502d7d6c6fb4da/src/rospy_service_bug/src/service_proxy.py#L33
- https://github.com/TinyTheBrontosaurus/rospy_service_bug/blob/4338f11662717d38fc63543987502d7d6c6fb4da/src/rospy_service_bug/src/service_proxy.py#L76

In all cases you should use `... = CustomMessage()` to create an instance rather then using the type.
