### ISSUE TITLE
how to transform the data type from .bag into data live stream

### ISSUE THREAD

**Issue by brianshu** [ros/ros_comm#968]
Sorry, I am new to ros, right now i am working on SLAM algo. with few api I am working on, all of them are using 2 terminal and readin data from rosbag. I just wondering is there anyway for me to readin data directly from my sensor which is a live data stream.

I asked these kind of noob questions to google cartographer in google group, the google's staff lead me to here.

please give me some advices what kind of package should i use in ros? or if rosbag could handle this case already, then how?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
