### ISSUE TITLE
rosbag: Recorder throws a segmentation fault if options.prefix is not set

### ISSUE THREAD

**Issue by diogoalmeida** [ros/ros_comm#969]
If I construct a ``rosbag::Recorder`` object with a ``rosbag::RecorderOptions`` where the member 'prefix' is not set, the ``recorder::run()`` method will segfault.

For instance, this code will segfault if the line ```options.prefix = "test";``` is commented out:

```cpp
#include <ros/ros.h>
#include <rosbag/recorder.h>

int main(int argc, char **argv)
{
  ros::init(argc, argv, "data_logger_test_node");
  ros::NodeHandle n;

  rosbag::RecorderOptions options;
  options.append_date = false;
  options.trigger = false;
  options.min_space = 0;
  options.verbose = true;
  options.prefix = "test";
  options.split = false;
  options.regex = false;
  options.topics.push_back("/rosout");
  options.max_duration = ros::Duration(1.0);

  rosbag::Recorder recorder(options);
  recorder.run();
}
```

**Comment by dirk-thomas** [comment]
Thank you for reporting this. The behavior is indeed bad. The [current code](https://github.com/ros/ros_comm/blob/8c430a800a93b155427fcbbac995fa6ea19f8937/tools/rosbag/src/recorder.cpp#L334-L351) determining the filename of the bag concatenates an optional `prefix`, an option `append_date` and an optional `split` count. Since you request neither of the three the resulting filename would be empty which the code doesn't handle nicely (see last highlighted line). I have created #971 to throw an exception in this case rather then segfault.
